[package]
name = "esp32c3-ble-hid"
version = "0.1.0"
authors = ["bjoernQ <bjoern.quentin@mobile-j.de>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
hal = { package = "esp32c3-hal", version = "0.13.0", features = [
    "embassy",
    "embassy-time-timg0",
] }
esp-backtrace = { version = "0.9.0", features = [
    "esp32c3",
    "panic-handler",
    "exception-handler",
    "print-uart",
] }
esp-println = { version = "0.7.0", features = ["esp32c3", "log"] }
esp-wifi = { version = "0.1.1", features = ["esp32c3", "ble", "async"] }
embassy-executor = { version = "=0.3.2", features = [
    "nightly",
    "executor-thread",
    "integrated-timers",
    "arch-riscv32",
] }
embassy-sync = { version = "0.4.0", features = ["nightly"] }
bleps = { git = "https://github.com/bjoernQ/bleps.git", rev = "6d9f2e7e726cb389334eb500a086fd2129069abc", package = "bleps", features = [
    "macros",
    "async",
    "crypto",
] }
rand_core = { version = "0.6.4" }
embedded-hal-async = { version = "1.0.0-rc.1" }
static_cell = { version = "=1.2.0", features = ["nightly"] }
embassy-time = { version = "0.1.5", features = ["nightly"] }
